# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Demo-DevOpsServiceConnection'
    subscriptionId: '6736e259-c1d5-401d-beee-19d2e1f05adc'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'KPMG-DEMO'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/Yashjain3127/Demo-Storage-ARM.git'
    overrideParameters: '-projectName Demo-project'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployStoragePipelineTemplate'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
